# This workflow sends discord notification through webhooks

name: Discord Notification

# The workflow runs on every Pull Request created
on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The workflow job name
  discord-notifier:
    # Name of the enviroment
    environment: secrets
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Sequence of tasks
    steps:
      - name: Discord Notification
        uses: tenzin1308/discord-notification@v1.0.0
        with:
          discord-webhook-url: ${{ secrets.WEBHOOKS_URL }}
